name: Sample Matrix Parallel

# on: push
 
on:
    workflow_dispatch:
 
jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        run: ['run1', 'run2']
    steps:
    - run: echo Run ${{ matrix.run }}
    - run: date
